# Default values for podinfo chart.
replicaCount: 1
namespace: flux-dev1

image:
  repository: ltbproject/self-service-password
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "64Mi"
    cpu: "101m"

